### ISSUE TITLE
In get_all_data self is missing

### ISSUE THREAD

**Issue by wenzelin** [Tijndagamer/MPU-6050-Python#13]
Code should be: 

    def get_all_data(self):
        """Reads and returns all the available data."""
        temp = self.get_temp()
        accel = self.get_accel_data()
        gyro = self.get_gyro_data()

        return [accel, gyro, temp]

**Comment by m-rtijn** [comment]
Fixed in commit 4fbbf21365cfd63683d66d69a2ca217487bec40a
