### ISSUE TITLE
Not defined

### ISSUE THREAD

**Issue by tmccoy33** [Tijndagamer/MPU-6050-Python#14]
So I in fact am a little new to programming, however ive used sample code from here a few times successfully. I'm running into an issue with yours however. When I go to run the sample code with my mpu6050, it's telling me that line 6 "from mpu6050 import mpu6050" there is an import error and that no module exists. Its also said in your other code that mpu6050 line 2xx "mpu6050" is undefined. I am sure I'm missing something that I didn't install from you or something of this nature. Could you please provide some insight as to what could possibly fix my issue? Thank you.

**Comment by m-rtijn** [comment]
Could you copy the exact error?

**Comment by m-rtijn** [comment]
If you have a problem with the `smbus-cffi` module, remove [line 21 from setup.py](https://github.com/Tijndagamer/mpu6050/blob/master/setup.py#L21) and install the `python-smbus` package.

**Comment by tmccoy33** [comment]
i removed line 1, it is saying this:


Traceback (most recent call last):
  File "/home/pi/mpu6050/bin/mpu6050-example.py", line 6, in <module>
    from mpu6050 import mpu6050
ImportError: No module named 'mpu6050'



________________________________

**Comment by tmccoy33** [comment]
sorry, i meant i removed line 21



________________________________

**Comment by m-rtijn** [comment]
It seems like you didn't install it (correctly).

Run the following command in the root directory of the repository in order to install the module to your system:
```
sudo pyton setup.py install
```

**Comment by sutanu86** [comment]
same error..... 
 from mpu6050 import mpu6050
ImportError: No module named 'mpu6050'
