### ISSUE TITLE
I0Error

### ISSUE THREAD

**Issue by mspalluzzi** [Tijndagamer/MPU-6050-Python#15]
Hey, seems like I've gotten the module installed correctly but when trying to run some sample code just to check if it will compile:

`from time import sleep
import RPi.GPIO as GPIO
from mpu6050 import mpu6050

sensor = mpu6050(0x68)

while True:
    accel_data = sensor.get_accel_data()
    gyro_data = sensor.get_gyrp_data()
    temp = sensor.get_temp()
`
I get this error:

![2017-04-30-105728_1824x984_scrot](https://cloud.githubusercontent.com/assets/28010216/25565458/f3192104-2d94-11e7-8e10-77da280fa8b8.png)

Any ideas what that may be referring to / how to fix?
Looking into that directory it seems like all the files are properly placed.
Using Pi 3 if that changes anything.

Thanks!

**Comment by Jimit04** [comment]
Run code with sudo.

**Comment by m-rtijn** [comment]
Thank you for using my module!

As @Jimit04 stated, you need to run the code using sudo to get access to the I2C bus.

**Comment by mspalluzzi** [comment]
Thanks for the quick response!
However, trying to run the code with sudo I'm getting the same error.

I did notice that I didnt do the pip install using sudo (seems like that would need elevated privileges?) so I went back through the whole process using sudo and I got the same error.

**Comment by m-rtijn** [comment]
Check if you have enabled I2C with raspi-config.

**Comment by mspalluzzi** [comment]
There it is!

Thanks for the help and the great module!

**Comment by m-rtijn** [comment]
No problem.
