### ISSUE TITLE
'module' object is not callable

### ISSUE THREAD

**Issue by GRhOGS** [Tijndagamer/MPU-6050-Python#22]
when I try to run the example code:

from mpu6050 import mpu6050
sensor = mpu6050(0x68)
print(sensor.get_accel_data())

It prints out an error on line 2 stating: 'module' object is not callable
I've installed it correctly, and there's no error when importing the module

**Comment by m-rtijn** [comment]
Hi @Georg2K2, thank you for using my library!

I have only been able to reproduce this issue by incorrectly importing the module.

```python
>>> import mpu6050
>>> sensor = mpu6050(0x68)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
```

You can either import the module using `from mpu6050 import mpu6050` and call the class constructor with `mpu6050(0x68)` or import the module using `import mpu6050` and call the constructor with `mpu6050.mpu6050(0x68)`.

I hope this fixes your issue.

**Comment by GRhOGS** [comment]
Like stated above, I import the module like:
from mpu6050 import mpu6050
and use it like described by you, but it still doesnt work for me :c

**Comment by m-rtijn** [comment]
Hm. That is really weird. Does the example script (in the repository `bin/mpu6050-example`) work for you?

**Comment by GRhOGS** [comment]
I get the error: No module named 'mpu6050'
I tried running the setup.py again, sadly it doesn't work. (also you might edit the instructions from "python setup.py install" to "sudo python setup.py install")
I tried doing the pip install, restarted and now I get "TypeError: 'module' object is not callable" on the example script

**Comment by m-rtijn** [comment]
Which version of python are you using? If your system has both python 2.7.x and python 3, are you consistently using the same python version while testing?

**Comment by GRhOGS** [comment]
im using python python 3

**Comment by GRhOGS** [comment]
but I got it working now on Python 2.7.13!

**Comment by m-rtijn** [comment]
Nice that it works now, could you maybe explain what you did differently with python 2.7? In the case that someone else might ever stumble on the same issue as you.

**Comment by GRhOGS** [comment]
I just launched the script with python 2 instead of 3... ¯\_(ツ)_/¯

**Comment by tmubashshira** [comment]
> I just launched the script with python 2 instead of 3... ¯_(ツ)_/¯

can you please tell the command you used to launch python 2 in raspberry pi??? I'm having the same error.....

**Comment by tmubashshira** [comment]
> I just launched the script with python 2 instead of 3... ¯_(ツ)_/¯

if you're using python 2, doesn't it create problem in other operations???

**Comment by GRhOGS** [comment]
I didn't run into any other problems... I haven't used that pi in years, I would have to google it again as well, sorry :/ maybe something like 'python2.7' in cmd, I'm not a huge Ubuntu buff...
