### ISSUE TITLE
no checking connectivity

### ISSUE THREAD

**Issue by Maxcullen** [Tijndagamer/MPU-6050-Python#23]
after cloning the file, everything works but i don't get the line that says checking connectivity... done.
the next line 'python setup.py install' seems to have no action then because it cannot find the file

**Comment by m-rtijn** [comment]
What host device are you using? Could you share the output you're seeing?

**Comment by Maxcullen** [comment]
I'm using a raspberry pi zero w. I am a bit of a noob so I apologize for my ignorance. I think it may not matter cause I went on with the programming and so far it looks good but I haven't had a chance to finish it all yet. I'd attach a photo but I can't get it up till tomorrow and didn't take one before. 
I really appreciate the assistance!
