### ISSUE TITLE
AttributeError: 'int' object has no attribute 'read_i2c_word'

### ISSUE THREAD

**Issue by vinayb1012** [Tijndagamer/MPU-6050-Python#25]
`sensor = mpu6050(0x68)`

Running this gives the following error - 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/mpu6050/mpu6050.py", line 139, in get_accel_data
    x = self.read_i2c_word(self.ACCEL_XOUT0)
AttributeError: 'int' object has no attribute 'read_i2c_word'

**Comment by m-rtijn** [comment]
Hey @vinayb1012, could you maybe give some more context? On which platform are you running the code? Which exact version of python? How did you install the mpu6050 package? What is the exact code you are executing?
