### ISSUE TITLE
Raspberry Pi - No Accelerometer Data Detected

### ISSUE THREAD

**Issue by cherbin** [Tijndagamer/MPU-6050-Python#28]
The raspberry pi is always getting zeros for the Accelerometer data.
Accelerometer data. Do you know the reason ?
x: 0.0
y: 0.0
z: 0.0
Gyroscope data
x: -156.183206107
y: 0.0
z: 0.0
Temp: 43.1182352941 C

root@raspberrypi:/opt/CANBUS/GYRO/py3/6050/mpu6050/bin#  sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

**Comment by m-rtijn** [comment]
Hm. I've never had this problem before. Maybe your MPU-6050 is defective? Do you maybe have multiple to test if the problem persists?

**Comment by m-rtijn** [comment]
I am closing this issue due to lack of response
