### ISSUE TITLE
Documentation overhaul

### ISSUE THREAD

**Issue by Descent098** [Tijndagamer/MPU-6050-Python#32]
I am just looking into this module and it seems interesting, would you be interested in me going through and re-vamping the docstrings and then generating a GitHub pages compatible docs site to make the package a bit more accessible (this is a free service by GitHub, there is no associated hosting fee)?

An example of what this would look like can be found [here](https://kieranwood.ca/sdu)

I want to check first before doing all the work and having no one on the team be interested, let me know if you have any questions or are interested.

Thanks!

**Comment by m-rtijn** [comment]
Hey @Descent098,

Thanks for the offer, but I have no interest in completely overhauling the documentation. If you have specific things that could be improved, please create a pull request.
