### ISSUE TITLE
MODULE ERROR

### ISSUE THREAD

**Issue by Sudo-AA** [Tijndagamer/MPU-6050-Python#35]
Traceback (most recent call last):
  File "HTR.py", line 6, in <module>
    mpu = mpu6050(0x68)
TypeError: 'module' object is not callable

**Comment by m-rtijn** [comment]
You get this error if you import the module just as is (`import mpu6050`). If you want to directly be able to create a new object, import the module like this: `from mpu6050 import mpu6050`.

Also see the example script in the repository: https://github.com/m-rtijn/mpu6050/blob/199af071aea8f7e973f8dbe634c69089a4a1046b/bin/mpu6050-example#L6-L9
