### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by ronnifadhlillah** [Tijndagamer/MPU-6050-Python#38]
How to know the register map of MPU 6050 without a documentation ? by the way thank you.

**Comment by m-rtijn** [comment]
You can find the MPU 6050 register map here: https://cdn.sparkfun.com/datasheets/Sensors/Accelerometers/RM-MPU-6000A.pdf

**Comment by ronnifadhlillah** [comment]
Hallo @m-rtijn , by the way thank you for the answer. But can i know the register map using code ? not documentation.

**Comment by m-rtijn** [comment]
> Hallo @m-rtijn , by the way thank you for the answer. But can i know the register map using code ? not documentation.

I'm not sure what you mean by this. Are you looking for the i2c address of the mpu6050 chip? If so, you can find it using [`i2cdetect`](https://linux.die.net/man/8/i2cdetect).

**Comment by ronnifadhlillah** [comment]
thank you for the answer. i've try to use i2detect but the result is not what i expected. i2detect can detect i2c device address but i want to know slave address of i2c device. 

For example i use mpu6050 in hex is 0x68 but i want to know a hex / address of GYRO_CONFIG (based on the documentation the gyro_config address is 0x1B). If i dont have a documentation how to proof that GYRO_CONFIG address is 0x1B.

**Comment by m-rtijn** [comment]
That is not possible. The register map from the manufacturer about the sensor is the only way to find this type of information.

**Comment by ronnifadhlillah** [comment]
Hallo @m-rtijn ,understood. Thank you for the answer , i appreciate your answer.
